name: cwagnerphotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41903
title: Candid Fine Art Documentary Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#93a1ae'
    - '#291f1e'
    - '#c1bfc0'
    - '#f6e6d9'
    - '#5a676f'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.524439848959446
  rhythmicContrast: 0.5
purpose: []
