name: cwagnerphotography
favicon: null
layout_spectrum: 0.8940930480603129
typography_spectrum: 0.7761090458370745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#93a1ae'
    - '#291f1e'
    - '#c1bfc0'
    - '#f6e6d9'
    - '#5a676f'
  brandStrength: 0.2713630369398743
  lightness: 0.45448910258710384
  saturation: 0.524439848959446
  rhythmicContrast: 0.6872431680094451
purpose: []
